# Generated by Django 3.2.7 on 2021-09-30 02:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20210929_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='date')),
                ('goal', models.IntegerField(default=0, verbose_name='daily goal (sec)')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dailyInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.daily'),
        ),
    ]
