# Generated by Django 3.2.7 on 2021-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20210930_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.CharField(max_length=10, null=True, verbose_name="user's style"),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
